CREATE TABLE alumnos (
	idAlumno TINYINT UNSIGNED PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL UNIQUE,
	pwd VARCHAR(50) NOT NULL,
	nombreJesuita VARCHAR(50) NOT NULL,
	descripcionJesuita VARCHAR(200) NOT NULL,
	imagenJesuita VARCHAR(100) NOT NULL
);